function getEnLocalization() {
    return {
        TITLE: 'Certificates',
        LOGIN: 'Login',
        LOGOUT: 'Logout',
        LANGUAGE: 'Language',
        ALL: 'All',
        MY_CERTIFICATES: 'My certificates',
        DESCRIPTION: 'Description',
        PRICE: 'Price',
        DURATION: 'Duration in days',
        DATE_OF_CREATION: 'Date of creation',
        DATE_OF_MODIFICATION: 'Date of modification',
        BUY: 'Buy',
        DELETE: 'Delete',
        EDIT: 'Edit',
        ADD_CERTIFICATE: 'Add new certificate',
        SEARCH: 'Go!',
        GIFT_CERTIFICATES: 'Gift Certificates',
        SIGN_UP: 'Sign Up',
        SIGN_IN: 'Sign In',
        LOGIN: 'Login',
        CANCEL: 'Cancel',
        TITLE_SIGN_IN: 'Sign In',
        PASSWORD: 'Password',
        LABEL_LOGIN: 'Login',
        REQUIRED_FIELD: 'Required field',
        NOT_CORRECT_SYMBOL: 'Not correct symbol',
        USERNAME_LARGE: 'Login is too large',
        USERNAME_SHORT: 'Login is too short',
        PASSWORD_LARGE: 'Password is too large',
        PASSWORD_SHORT: 'Password is too short',
        ENTER_PASSWORD: 'Enter password',
        ENTER_LOGIN: 'Enter your login',
        ENTER_CERTIFICATE_NAME: 'Enter certificate name',
        ENTER_CERTIFICATE_DESCRIPTION: 'Enter certificate description',
        ENTER_PRICE: 'Enter price',
        ENTER_DURATION: 'Enter duration',
        ENTER_TAG_NAME: 'Enter tag name',
        TITLE_SIGN_UP: 'Sign Up',
        ADD_CERTIFICATE_TITLE: 'Add certificate',
        NAME_FIELD: 'Name',
        ADD: 'Add',
        TAG: 'Tag',
        CERTIFICATE_NAME_LARGE: 'Certificate name is too large',
        CERTIFICATE_NAME_SHORT: 'Certificate name is too short',
        CERTIFICATE_DESCRIPTION_SHORT: 'Certificate description is too short',
        CERTIFICATE_DURATION_MIN: 'Min value of the certificate duration must be 1',
        CERTIFICATE_DURATION_MAX: 'Max value of the certificate duration must be 31',
        CERTIFICATE_PRICE_MIN: 'Min value of the certificate price must be 1',
        EDIT_CERTIFICATE: 'Edit certificate',
        DELETE_MESSAGE: 'Do you want to delete this certificate?',
        DELETE_SUCCESS_CERTIFICATE: 'Certificate successfully deleted.',
        PURCHASE_CERTIFICATE: 'Certificate purchased successfully.',
        ADD_CERTIFICATE_MESSAGE: 'Certificate successfully added.',
        UPDATE_CERTIFICATE_MESSAGE: 'Certificate successfully updated.',
        INCORRECT_DATA: 'The data entered is incorrect',
        UNSAVED_DATA: 'You have unsaved data. Do you want to leave this page?',
        LIMIT: 'Limit',
        FIRST: 'First',
        LAST: 'Last',
        SEARCH_PLACEHOLDER: 'Search...'
      };  
}

function getRuLocalization() {
    return {
        TITLE: 'Сертификаты',
        LOGIN: 'Войти',
        LOGOUT: 'Выйти',
        LANGUAGE: 'Язык',
        ALL: 'Все',
        MY_CERTIFICATES: 'Мои сертификаты',
        DESCRIPTION: 'Описание',
        PRICE: 'Цена',
        DURATION: 'Продолжительность в днях',
        DATE_OF_CREATION: 'Дата создания',
        DATE_OF_MODIFICATION: 'Дата изменения',
        BUY: 'Купить',
        DELETE: 'Удалить',
        EDIT: 'Изменить',
        ADD_CERTIFICATE: 'Добавить сертификат',
        SEARCH: 'Поиск',
        GIFT_CERTIFICATES: 'Подарочные Сертификаты',
        SIGN_UP: 'Регистрация',
        SIGN_IN: 'Войти',
        LOGIN: 'Войти',
        CANCEL: 'Отмена',
        TITLE_SIGN_IN: 'Вход',
        PASSWORD: 'Пароль',
        LABEL_LOGIN: 'Имя пользователя',
        REQUIRED_FIELD: 'Обязательное поле',
        NOT_CORRECT_SYMBOL: 'Некорректный символ',
        USERNAME_LARGE: 'Имя пользователя очень длинное',
        USERNAME_SHORT: 'Короткое имя пользователя',
        PASSWORD_LARGE: 'Пароль очень длинный',
        PASSWORD_SHORT: 'Короткий пароль',
        ENTER_PASSWORD: 'Введите пароль',
        ENTER_LOGIN: 'Введите имя пользователя',
        ENTER_CERTIFICATE_NAME: 'Введите название сертификата',
        ENTER_CERTIFICATE_DESCRIPTION: 'Введите описание сертификата',
        ENTER_PRICE: 'Введите цену',
        ENTER_DURATION: 'Введите продолжительность',
        ENTER_TAG_NAME: 'Введите тэг',
        TITLE_SIGN_UP: 'Регистрация',
        ADD_CERTIFICATE_TITLE: 'Добавить сертификат',
        NAME_FIELD: 'Название',
        ADD: 'Добавить',
        TAG: 'Тэг',
        CERTIFICATE_NAME_LARGE: 'Очень длинное имя сертификата',
        CERTIFICATE_NAME_SHORT: 'Короткое имя сертификата',
        CERTIFICATE_DESCRIPTION_SHORT: 'Короткое описание сертификата',
        CERTIFICATE_DURATION_MIN: 'Минимальное значение срока действия сертификата должно быть 1',
        CERTIFICATE_DURATION_MAX: 'Максимальное значение срока действия сертификата должно быть 31',
        CERTIFICATE_PRICE_MIN: 'Минимальное значение цены сертификата должно быть 1',
        EDIT_CERTIFICATE: 'Изменить сертификат',
        DELETE_MESSAGE: 'Вы действительно хотите удалить сертификат?',
        DELETE_SUCCESS_CERTIFICATE: 'Сертификат успешно удален.',
        PURCHASE_CERTIFICATE: 'Сертификат успешно приобретен.',
        ADD_CERTIFICATE_MESSAGE: 'Сертификат успешно добавлен.',
        UPDATE_CERTIFICATE_MESSAGE: 'Сертификат успешно обновлен.',
        INCORRECT_DATA: 'Введенные данные некорректны',
        UNSAVED_DATA: 'У вас есть несохраненная информация. Вы дейсвительно хотите покинуть страницу?',
        LIMIT: 'Лимит',
        FIRST: 'Первый',
        LAST: 'Последний',
        SEARCH_PLACEHOLDER: 'Поиск...'
      }
}

export {getEnLocalization, getRuLocalization};